modLoader="javafml"
loaderVersion="[28,)"
logoFile="logo.png"
issueTrackerURL="https://github.com/Darkhax-Minecraft/Bookshelf/issues"

[[mods]]
modId="bookshelf"
version="${version}"
displayName="${mod_name}"
displayURL="${mod_download}"
credits="${mod_credits}"
authors="${mod_authors}"
description='''
${mod_description}
'''

[[dependencies.bookshelf]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bookshelf]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"